<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['country_name' => 'Afghanistan', 'country_code' => 'AFG', 'code' => 'AF'],
            ['country_name' => 'Albania', 'country_code' => 'ALB', 'code' => 'AL'],
            ['country_name' => 'Algeria', 'country_code' => 'DZA', 'code' => 'DZ'],
            ['country_name' => 'American Samoa', 'country_code' => 'ASM', 'code' => 'AS'],
            ['country_name' => 'Andorra', 'country_code' => 'AND', 'code' => 'AD'],
            ['country_name' => 'Angola', 'country_code' => 'AGO', 'code' => 'AO'],
            ['country_name' => 'Anguilla', 'country_code' => 'AIA', 'code' => 'AI'],
            ['country_name' => 'Antarctica', 'country_code' => 'ATA', 'code' => 'AQ'],
            ['country_name' => 'Antigua and Barbuda', 'country_code' => 'ATG', 'code' => 'AG'],
            ['country_name' => 'Argentina', 'country_code' => 'ARG', 'code' => 'AR'],
            ['country_name' => 'Armenia', 'country_code' => 'ARM', 'code' => 'AM'],
            ['country_name' => 'Aruba', 'country_code' => 'ABW', 'code' => 'AW'],
            ['country_name' => 'Australia', 'country_code' => 'AUS', 'code' => 'AU'],
            ['country_name' => 'Austria', 'country_code' => 'AUT', 'code' => 'AT'],
            ['country_name' => 'Azerbaijan', 'country_code' => 'AZE', 'code' => 'AZ'],
            ['country_name' => 'Bahamas', 'country_code' => 'BHS', 'code' => 'BS'],
            ['country_name' => 'Bahrain', 'country_code' => 'BHR', 'code' => 'BH'],
            ['country_name' => 'Bangladesh', 'country_code' => 'BGD', 'code' => 'BD'],
            ['country_name' => 'Barbados', 'country_code' => 'BRB', 'code' => 'BB'],
            ['country_name' => 'Belarus', 'country_code' => 'BLR', 'code' => 'BY'],
            ['country_name' => 'Belgium', 'country_code' => 'BEL', 'code' => 'BE'],
            ['country_name' => 'Belize', 'country_code' => 'BLZ', 'code' => 'BZ'],
            ['country_name' => 'Benin', 'country_code' => 'BEN', 'code' => 'BJ'],
            ['country_name' => 'Bermuda', 'country_code' => 'BMU', 'code' => 'BM'],
            ['country_name' => 'Bhutan', 'country_code' => 'BTN', 'code' => 'BT'],
            ['country_name' => 'Bolivia', 'country_code' => 'BOL', 'code' => 'BO'],
            ['country_name' => 'Bosnia and Herzegovina', 'country_code' => 'BIH', 'code' => 'BA'],
            ['country_name' => 'Botswana', 'country_code' => 'BWA', 'code' => 'BW'],
            ['country_name' => 'Brazil', 'country_code' => 'BRA', 'code' => 'BR'],
            ['country_name' => 'British Virgin Islands', 'country_code' => 'VGB', 'code' => 'VG'],
            ['country_name' => 'Brunei', 'country_code' => 'BRN', 'code' => 'BN'],
            ['country_name' => 'Bulgaria', 'country_code' => 'BGR', 'code' => 'BG'],
            ['country_name' => 'Burkina Faso', 'country_code' => 'BFA', 'code' => 'BF'],
            ['country_name' => 'Burundi', 'country_code' => 'BDI', 'code' => 'BI'],
            ['country_name' => 'Cambodia', 'country_code' => 'KHM', 'code' => 'KH'],
            ['country_name' => 'Cameroon', 'country_code' => 'CMR', 'code' => 'CM'],
            ['country_name' => 'Canada', 'country_code' => 'CAN', 'code' => 'CA'],
            ['country_name' => 'Cape Verde', 'country_code' => 'CPV', 'code' => 'CV'],
            ['country_name' => 'Cayman Islands', 'country_code' => 'CYM', 'code' => 'KY'],
            ['country_name' => 'Central African Republic', 'country_code' => 'CAF', 'code' => 'CF'],
            ['country_name' => 'Chad', 'country_code' => 'TCD', 'code' => 'TD'],
            ['country_name' => 'Chile', 'country_code' => 'CHL', 'code' => 'CL'],
            ['country_name' => 'China', 'country_code' => 'CHN', 'code' => 'CN'],
            ['country_name' => 'Colombia', 'country_code' => 'COL', 'code' => 'CO'],
            ['country_name' => 'Comoros', 'country_code' => 'COM', 'code' => 'KM'],
            ['country_name' => 'Cook Islands', 'country_code' => 'COK', 'code' => 'CK'],
            ['country_name' => 'Costa Rica', 'country_code' => 'CRI', 'code' => 'CR'],
            ['country_name' => 'Croatia', 'country_code' => 'HRV', 'code' => 'HR'],
            ['country_name' => 'Cuba', 'country_code' => 'CUB', 'code' => 'CU'],
            ['country_name' => 'Curacao', 'country_code' => 'CUW', 'code' => 'CW'],
            ['country_name' => 'Cyprus', 'country_code' => 'CYP', 'code' => 'CY'],
            ['country_name' => 'Czech Republic', 'country_code' => 'CZE', 'code' => 'CZ'],
            ['country_name' => 'Democratic Republic of the Congo', 'country_code' => 'COD', 'code' => 'CD'],
            ['country_name' => 'Denmark', 'country_code' => 'DNK', 'code' => 'DK'],
            ['country_name' => 'Djibouti', 'country_code' => 'DJI', 'code' => 'DJ'],
            ['country_name' => 'Dominica', 'country_code' => 'DMA', 'code' => 'DM'],
            ['country_name' => 'Dominican Republic', 'country_code' => 'DOM', 'code' => 'DO'],
            ['country_name' => 'East Timor', 'country_code' => 'TLS', 'code' => 'TL'],
            ['country_name' => 'Ecuador', 'country_code' => 'ECU', 'code' => 'EC'],
            ['country_name' => 'Egypt', 'country_code' => 'EGY', 'code' => 'EG'],
            ['country_name' => 'El Salvador', 'country_code' => 'SLV', 'code' => 'SV'],
            ['country_name' => 'Equatorial Guinea', 'country_code' => 'GNQ', 'code' => 'GQ'],
            ['country_name' => 'Eritrea', 'country_code' => 'ERI', 'code' => 'ER'],
            ['country_name' => 'Estonia', 'country_code' => 'EST', 'code' => 'EE'],
            ['country_name' => 'Ethiopia', 'country_code' => 'ETH', 'code' => 'ET'],
            ['country_name' => 'Falkland Islands', 'country_code' => 'FLK', 'code' => 'FK'],
            ['country_name' => 'Faroe Islands', 'country_code' => 'FRO', 'code' => 'FO'],
            ['country_name' => 'Fiji', 'country_code' => 'FJI', 'code' => 'FJ'],
            ['country_name' => 'Finland', 'country_code' => 'FIN', 'code' => 'FI'],
            ['country_name' => 'France', 'country_code' => 'FRA', 'code' => 'FR'],
            ['country_name' => 'French Polynesia', 'country_code' => 'PYF', 'code' => 'PF'],
            ['country_name' => 'Gabon', 'country_code' => 'GAB', 'code' => 'GA'],
            ['country_name' => 'Gambia', 'country_code' => 'GMB', 'code' => 'GM'],
            ['country_name' => 'Georgia', 'country_code' => 'GEO', 'code' => 'GE'],
            ['country_name' => 'Germany', 'country_code' => 'DEU', 'code' => 'DE'],
            ['country_name' => 'Ghana', 'country_code' => 'GHA', 'code' => 'GH'],
            ['country_name' => 'Gibraltar', 'country_code' => 'GIB', 'code' => 'GI'],
            ['country_name' => 'Greece', 'country_code' => 'GRC', 'code' => 'GR'],
            ['country_name' => 'Greenland', 'country_code' => 'GRL', 'code' => 'GL'],
            ['country_name' => 'Grenada', 'country_code' => 'GRD', 'code' => 'GD'],
            ['country_name' => 'Guam', 'country_code' => 'GUM', 'code' => 'GU'],
            ['country_name' => 'Guatemala', 'country_code' => 'GTM', 'code' => 'GT'],
            ['country_name' => 'Guernsey', 'country_code' => 'GGY', 'code' => 'GG'],
            ['country_name' => 'Guinea', 'country_code' => 'GIN', 'code' => 'GN'],
            ['country_name' => 'Guinea-Bissau', 'country_code' => 'GNB', 'code' => 'GW'],
            ['country_name' => 'Guyana', 'country_code' => 'GUY', 'code' => 'GY'],
            ['country_name' => 'Haiti', 'country_code' => 'HTI', 'code' => 'HT'],
            ['country_name' => 'Honduras', 'country_code' => 'HND', 'code' => 'HN'],
            ['country_name' => 'Hong Kong', 'country_code' => 'HKG', 'code' => 'HK'],
            ['country_name' => 'Hungary', 'country_code' => 'HUN', 'code' => 'HU'],
            ['country_name' => 'Iceland', 'country_code' => 'ISL', 'code' => 'IS'],
            ['country_name' => 'India', 'country_code' => 'IND', 'code' => 'IN'],
            ['country_name' => 'Indonesia', 'country_code' => 'IDN', 'code' => 'ID'],
            ['country_name' => 'Iran', 'country_code' => 'IRN', 'code' => 'IR'],
            ['country_name' => 'Iraq', 'country_code' => 'IRQ', 'code' => 'IQ'],
            ['country_name' => 'Ireland', 'country_code' => 'IRL', 'code' => 'IE'],
            ['country_name' => 'Isle of Man', 'country_code' => 'IMN', 'code' => 'IM'],
            ['country_name' => 'Israel', 'country_code' => 'ISR', 'code' => 'IL'],
            ['country_name' => 'Italy', 'country_code' => 'ITA', 'code' => 'IT'],
            ['country_name' => 'Ivory Coast', 'country_code' => 'CIV', 'code' => 'CI'],
            ['country_name' => 'Jamaica', 'country_code' => 'JAM', 'code' => 'JM'],
            ['country_name' => 'Japan', 'country_code' => 'JPN', 'code' => 'JP'],
            ['country_name' => 'Jersey', 'country_code' => 'JEY', 'code' => 'JE'],
            ['country_name' => 'Jordan', 'country_code' => 'JOR', 'code' => 'JO'],
            ['country_name' => 'Kazakhstan', 'country_code' => 'KAZ', 'code' => 'KZ'],
            ['country_name' => 'Kenya', 'country_code' => 'KEN', 'code' => 'KE'],
            ['country_name' => 'Kiribati', 'country_code' => 'KIR', 'code' => 'KI'],
            ['country_name' => 'Kosovo', 'country_code' => 'XKX', 'code' => 'XK'],
            ['country_name' => 'Kuwait', 'country_code' => 'KWT', 'code' => 'KW'],
            ['country_name' => 'Kyrgyzstan', 'country_code' => 'KGZ', 'code' => 'KG'],
            ['country_name' => 'Laos', 'country_code' => 'LAO', 'code' => 'LA'],
            ['country_name' => 'Latvia', 'country_code' => 'LVA', 'code' => 'LV'],
            ['country_name' => 'Lebanon', 'country_code' => 'LBN', 'code' => 'LB'],
            ['country_name' => 'Lesotho', 'country_code' => 'LSO', 'code' => 'LS'],
            ['country_name' => 'Liberia', 'country_code' => 'LBR', 'code' => 'LR'],
            ['country_name' => 'Libya', 'country_code' => 'LBY', 'code' => 'LY'],
            ['country_name' => 'Liechtenstein', 'country_code' => 'LIE', 'code' => 'LI'],
            ['country_name' => 'Lithuania', 'country_code' => 'LTU', 'code' => 'LT'],
            ['country_name' => 'Luxembourg', 'country_code' => 'LUX', 'code' => 'LU'],
            ['country_name' => 'Macau', 'country_code' => 'MAC', 'code' => 'MO'],
            ['country_name' => 'Macedonia', 'country_code' => 'MKD', 'code' => 'MK'],
            ['country_name' => 'Madagascar', 'country_code' => 'MDG', 'code' => 'MG'],
            ['country_name' => 'Malawi', 'country_code' => 'MWI', 'code' => 'MW'],
            ['country_name' => 'Malaysia', 'country_code' => 'MYS', 'code' => 'MY'],
            ['country_name' => 'Maldives', 'country_code' => 'MDV', 'code' => 'MV'],
            ['country_name' => 'Mali', 'country_code' => 'MLI', 'code' => 'ML'],
            ['country_name' => 'Malta', 'country_code' => 'MLT', 'code' => 'MT'],
            ['country_name' => 'Marshall Islands', 'country_code' => 'MHL', 'code' => 'MH'],
            ['country_name' => 'Mauritania', 'country_code' => 'MRT', 'code' => 'MR'],
            ['country_name' => 'Mauritius', 'country_code' => 'MUS', 'code' => 'MU'],
            ['country_name' => 'Mexico', 'country_code' => 'MEX', 'code' => 'MX'],
            ['country_name' => 'Micronesia', 'country_code' => 'FSM', 'code' => 'FM'],
            ['country_name' => 'Moldova', 'country_code' => 'MDA', 'code' => 'MD'],
            ['country_name' => 'Monaco', 'country_code' => 'MCO', 'code' => 'MC'],
            ['country_name' => 'Mongolia', 'country_code' => 'MNG', 'code' => 'MN'],
            ['country_name' => 'Montenegro', 'country_code' => 'MNE', 'code' => 'ME'],
            ['country_name' => 'Montserrat', 'country_code' => 'MSR', 'code' => 'MS'],
            ['country_name' => 'Morocco', 'country_code' => 'MAR', 'code' => 'MA'],
            ['country_name' => 'Mozambique', 'country_code' => 'MOZ', 'code' => 'MZ'],
            ['country_name' => 'Myanmar', 'country_code' => 'MMR', 'code' => 'MM'],
            ['country_name' => 'Namibia', 'country_code' => 'NAM', 'code' => 'NA'],
            ['country_name' => 'Nauru', 'country_code' => 'NRU', 'code' => 'NR'],
            ['country_name' => 'Nepal', 'country_code' => 'NPL', 'code' => 'NP'],
            ['country_name' => 'Netherlands', 'country_code' => 'NLD', 'code' => 'NL'],
            ['country_name' => 'New Caledonia', 'country_code' => 'NCL', 'code' => 'NC'],
            ['country_name' => 'New Zealand', 'country_code' => 'NZL', 'code' => 'NZ'],
            ['country_name' => 'Nicaragua', 'country_code' => 'NIC', 'code' => 'NI'],
            ['country_name' => 'Niger', 'country_code' => 'NER', 'code' => 'NE'],
            ['country_name' => 'Nigeria', 'country_code' => 'NGA', 'code' => 'NG'],
            ['country_name' => 'Niue', 'country_code' => 'NIU', 'code' => 'NU'],
            ['country_name' => 'North Korea', 'country_code' => 'PRK', 'code' => 'KP'],
            ['country_name' => 'Northern Mariana Islands', 'country_code' => 'MNP', 'code' => 'MP'],
            ['country_name' => 'Norway', 'country_code' => 'NOR', 'code' => 'NO'],
            ['country_name' => 'Oman', 'country_code' => 'OMN', 'code' => 'OM'],
            ['country_name' => 'Pakistan', 'country_code' => 'PAK', 'code' => 'PK'],
            ['country_name' => 'Palau', 'country_code' => 'PLW', 'code' => 'PW'],
            ['country_name' => 'Palestine', 'country_code' => 'PSE', 'code' => 'PS'],
            ['country_name' => 'Panama', 'country_code' => 'PAN', 'code' => 'PA'],
            ['country_name' => 'Papua New Guinea', 'country_code' => 'PNG', 'code' => 'PG'],
            ['country_name' => 'Paraguay', 'country_code' => 'PRY', 'code' => 'PY'],
            ['country_name' => 'Peru', 'country_code' => 'PER', 'code' => 'PE'],
            ['country_name' => 'Philippines', 'country_code' => 'PHL', 'code' => 'PH'],
            ['country_name' => 'Pitcairn', 'country_code' => 'PCN', 'code' => 'PN'],
            ['country_name' => 'Poland', 'country_code' => 'POL', 'code' => 'PL'],
            ['country_name' => 'Portugal', 'country_code' => 'PRT', 'code' => 'PT'],
            ['country_name' => 'Puerto Rico', 'country_code' => 'PRI', 'code' => 'PR'],
            ['country_name' => 'Qatar', 'country_code' => 'QAT', 'code' => 'QA'],
            ['country_name' => 'Republic of the Congo', 'country_code' => 'COG', 'code' => 'CG'],
            ['country_name' => 'Reunion', 'country_code' => 'REU', 'code' => 'RE'],
            ['country_name' => 'Romania', 'country_code' => 'ROU', 'code' => 'RO'],
            ['country_name' => 'Russia', 'country_code' => 'RUS', 'code' => 'RU'],
            ['country_name' => 'Rwanda', 'country_code' => 'RWA', 'code' => 'RW'],
            ['country_name' => 'Saint Barthelemy', 'country_code' => 'BLM', 'code' => 'BL'],
            ['country_name' => 'Saint Helena', 'country_code' => 'SHN', 'code' => 'SH'],
            ['country_name' => 'Saint Kitts and Nevis', 'country_code' => 'KNA', 'code' => 'KN'],
            ['country_name' => 'Saint Lucia', 'country_code' => 'LCA', 'code' => 'LC'],
            ['country_name' => 'Saint Martin', 'country_code' => 'MAF', 'code' => 'MF'],
            ['country_name' => 'Saint Pierre and Miquelon', 'country_code' => 'SPM', 'code' => 'PM'],
            ['country_name' => 'Saint Vincent and the Grenadines', 'country_code' => 'VCT', 'code' => 'VC'],
            ['country_name' => 'Samoa', 'country_code' => 'WSM', 'code' => 'WS'],
            ['country_name' => 'San Marino', 'country_code' => 'SMR', 'code' => 'SM'],
            ['country_name' => 'Sao Tome and Principe', 'country_code' => 'STP', 'code' => 'ST'],
            ['country_name' => 'Saudi Arabia', 'country_code' => 'SAU', 'code' => 'SA'],
            ['country_name' => 'Senegal', 'country_code' => 'SEN', 'code' => 'SN'],
            ['country_name' => 'Serbia', 'country_code' => 'SRB', 'code' => 'RS'],
            ['country_name' => 'Seychelles', 'country_code' => 'SYC', 'code' => 'SC'],
            ['country_name' => 'Sierra Leone', 'country_code' => 'SLE', 'code' => 'SL'],
            ['country_name' => 'Singapore', 'country_code' => 'SGP', 'code' => 'SG'],
            ['country_name' => 'Sint Maarten', 'country_code' => 'SXM', 'code' => 'SX'],
            ['country_name' => 'Slovakia', 'country_code' => 'SVK', 'code' => 'SK'],
            ['country_name' => 'Slovenia', 'country_code' => 'SVN', 'code' => 'SI'],
            ['country_name' => 'Solomon Islands', 'country_code' => 'SLB', 'code' => 'SB'],
            ['country_name' => 'Somalia', 'country_code' => 'SOM', 'code' => 'SO'],
            ['country_name' => 'South Africa', 'country_code' => 'ZAF', 'code' => 'ZA'],
            ['country_name' => 'South Korea', 'country_code' => 'KOR', 'code' => 'KR'],
            ['country_name' => 'South Sudan', 'country_code' => 'SSD', 'code' => 'SS'],
            ['country_name' => 'Spain', 'country_code' => 'ESP', 'code' => 'ES'],
            ['country_name' => 'Sri Lanka', 'country_code' => 'LKA', 'code' => 'LK'],
            ['country_name' => 'Sudan', 'country_code' => 'SDN', 'code' => 'SD'],
            ['country_name' => 'Suriname', 'country_code' => 'SUR', 'code' => 'SR'],
            ['country_name' => 'Svalbard and Jan Mayen', 'country_code' => 'SJM', 'code' => 'SJ'],
            ['country_name' => 'Swaziland', 'country_code' => 'SWZ', 'code' => 'SZ'],
            ['country_name' => 'Sweden', 'country_code' => 'SWE', 'code' => 'SE'],
            ['country_name' => 'Switzerland', 'country_code' => 'CHE', 'code' => 'CH'],
            ['country_name' => 'Syria', 'country_code' => 'SYR', 'code' => 'SY'],
            ['country_name' => 'Taiwan', 'country_code' => 'TWN', 'code' => 'TW'],
            ['country_name' => 'Tajikistan', 'country_code' => 'TJK', 'code' => 'TJ'],
            ['country_name' => 'Tanzania', 'country_code' => 'TZA', 'code' => 'TZ'],
            ['country_name' => 'Thailand', 'country_code' => 'THA', 'code' => 'TH'],
            ['country_name' => 'Togo', 'country_code' => 'TGO', 'code' => 'TG'],
            ['country_name' => 'Tokelau', 'country_code' => 'TKL', 'code' => 'TK'],
            ['country_name' => 'Tonga', 'country_code' => 'TON', 'code' => 'TO'],
            ['country_name' => 'Trinidad and Tobago', 'country_code' => 'TTO', 'code' => 'TT'],
            ['country_name' => 'Tunisia', 'country_code' => 'TUN', 'code' => 'TN'],
            ['country_name' => 'Turkey', 'country_code' => 'TUR', 'code' => 'TR'],
            ['country_name' => 'Turkmenistan', 'country_code' => 'TKM', 'code' => 'TM'],
            ['country_name' => 'Turks and Caicos Islands', 'country_code' => 'TCA', 'code' => 'TC'],
            ['country_name' => 'Tuvalu', 'country_code' => 'TUV', 'code' => 'TV'],
            ['country_name' => 'U.S. Virgin Islands', 'country_code' => 'VIR', 'code' => 'VI'],
            ['country_name' => 'Uganda', 'country_code' => 'UGA', 'code' => 'UG'],
            ['country_name' => 'Ukraine', 'country_code' => 'UKR', 'code' => 'UA'],
            ['country_name' => 'United Arab Emirates', 'country_code' => 'ARE', 'code' => 'AE'],
            ['country_name' => 'United Kingdom', 'country_code' => 'GBR', 'code' => 'GB'],
            ['country_name' => 'United States', 'country_code' => 'USA', 'code' => 'US'],
            ['country_name' => 'Uruguay', 'country_code' => 'URY', 'code' => 'UY'],
            ['country_name' => 'Uzbekistan', 'country_code' => 'UZB', 'code' => 'UZ'],
            ['country_name' => 'Vanuatu', 'country_code' => 'VUT', 'code' => 'VU'],
            ['country_name' => 'Vatican', 'country_code' => 'VAT', 'code' => 'VA'],
            ['country_name' => 'Venezuela', 'country_code' => 'VEN', 'code' => 'VE'],
            ['country_name' => 'Vietnam', 'country_code' => 'VNM', 'code' => 'VN'],
            ['country_name' => 'Wallis and Futuna', 'country_code' => 'WLF', 'code' => 'WF'],
            ['country_name' => 'Western Sahara', 'country_code' => 'ESH', 'code' => 'EH'],
            ['country_name' => 'Yemen', 'country_code' => 'YEM', 'code' => 'YE'],
            ['country_name' => 'Zambia', 'country_code' => 'ZMB', 'code' => 'ZM'],
            ['country_name' => 'Zimbabwe', 'country_code' => 'ZWE', 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate (
                ['country_code' => $country['country_code']],
                $country
            );
        }
    }
}
